default: &default
  host: ENV["PG_HOST"]
  user: ENV["PG_USER"]
  password: ENV["PG_PASS"]
  adapter: postgres
  skip_dumping_schema_sql: true

development:
  <<: *default
  db: detransport_development

test:
  <<: *default
  db: detransport_test

production:
  <<: *default
  db: detransport_production
